console.log(typeof(null))
console.log(typeof(undefined))
console.log(typeof(1))
console.log(typeof(""))
console.log(typeof("a"))
console.log(typeof([]))
console.log(typeof({}))
console.log(typeof(true))
console.log(typeof("true"))
console.log(typeof(NaN))

console.log("***************************************************")
console.log(!!'false')
console.log([]==![])
console.log(null==undefined)
console.log(null===undefined)
console.log(null==0)
console.log(null===0)
console.log(NaN<=0)
console.log(undefined == 0)
console.log("0"==0)
console.log('0'===0)
console.log(0||'0'&&{})
console.log((typeof NaN)=="number")